In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[:4]  # Slicing means extracting a subsequence

array([1, 2, 3, 4])

In [5]:
arr_2d = np.array(([1, 2, 3], [4, 5, 6]))

In [8]:
arr_2d[0, 1]  # Only for numpy # Indexing means assessing to only a single unit

2

In [10]:
arr[-3:]

array([7, 8, 9])

In [11]:
arr_2d[:2, :2]

array([[1, 2],
       [4, 5]])

In [13]:
arr_2d[::2, ::2]

array([[1, 3]])

In [15]:
# Reshaping

a = np.arange(36).reshape(6, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [20]:
# Boolean Indexing or Masking
arr3 = np.array([1, 2, 3, 4])
mask = np.array([True, False, True, False])
arr3[mask]

# Or

mask2 = arr3 > 1
arr3[mask2]

# Or

arr3[arr3 > 1]

array([2, 3, 4])

In [21]:
# Fancy indexing is the way that instead of giving True or False we cna mention the indices that we want

arr4 = np.array([10, 20, 30, 40])
indices = np.array([1, 2])
arr4[indices]

array([20, 30])

In [22]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
row_indices = np.array([1])
col_indices = np.array([2])

arr_2d[row_indices, col_indices]

array([6])

In [23]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d[:1, [1, 2]]

array([[2, 3]])

In [26]:
# Array manipulation
arr = np.array([1, 2, 3])
arr[1] = 10
arr

array([ 1, 10,  3])

In [27]:
arr[np.array([True, True, False])] = 99
arr

array([99, 99,  3])

In [31]:
arr[np.array([1, 2])] = 105
arr

array([ 99, 105, 105])

In [35]:
# View vs Copy

# In numpy we do have view and we can have slices and also we can see the array from different perspectives

arr_view = arr[::2]
arr_view

# Copy

arr_copy = arr[::2].copy()
arr_copy

array([ 99, 105])