In [1]:
# In ndarray : 1) Scalar (only one number / rank 0 ) -- 2)1D array vector (one row of data / rank 1) -- 3)2D Array Matrix (2D data / rank 2) -- 4) 3D Array Tensor (3D data or more / rank 3)

In [2]:
import numpy as np

arr = np.array((1, 2, 3))
arr

array([1, 2, 3])

In [3]:
arr2 = np.array(range(1, 30))  # Here we cant use float seteps only int one are usable
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
arr3 = np.arange(1, 20, 0.5)
arr3

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5])

In [5]:
arr4 = np.linspace(
    1, 10, 40
)  # Instead of giving number of steps, we can choose to how many numbers we want to have among the range
arr4

array([ 1.        ,  1.23076923,  1.46153846,  1.69230769,  1.92307692,
        2.15384615,  2.38461538,  2.61538462,  2.84615385,  3.07692308,
        3.30769231,  3.53846154,  3.76923077,  4.        ,  4.23076923,
        4.46153846,  4.69230769,  4.92307692,  5.15384615,  5.38461538,
        5.61538462,  5.84615385,  6.07692308,  6.30769231,  6.53846154,
        6.76923077,  7.        ,  7.23076923,  7.46153846,  7.69230769,
        7.92307692,  8.15384615,  8.38461538,  8.61538462,  8.84615385,
        9.07692308,  9.30769231,  9.53846154,  9.76923077, 10.        ])

In [9]:
# Matrices

arr5 = np.array([[1, 2, 3, 4, 5], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])
arr5

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
arr6 = np.zeros((3, 3))  # Ones, eye, diag
arr6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# 3D arrays

arr7 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr7

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
arr7.shape

(2, 2, 3)

In [18]:
# Manipulating the numpy array datatype
# For the best practice always try to determine the data type by yourself

arr8 = np.array([1, 2, 3, 4], dtype=np.float64)
arr8

array([1., 2., 3., 4.])

In [20]:
# Random number generation
np.random.rand(3, 3)

array([[0.74397023, 0.79133568, 0.04168684],
       [0.93229841, 0.89210248, 0.17539579],
       [0.06157128, 0.7886299 , 0.09011244]])

In [21]:
# Standard normal distribution

np.random.randn(3, 3)

array([[ 0.43891176, -0.05242367, -0.00522643],
       [-1.38823929,  1.69310209, -1.96597134],
       [-0.3321333 , -0.11071672, -0.91566876]])

In [25]:
np.random.randint(low=2, high=10, size=(3, 3))

array([[6, 3, 9],
       [8, 6, 6],
       [2, 2, 5]])